# Generated by Django 4.2.7 on 2024-01-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='message',
            new_name='Symptoms',
        ),
        migrations.AddField(
            model_name='appointment',
            name='Email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
